// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7EAZbKYOCMELCun4rv9Oahvci0DRtos',
    appId: '1:1057753587696:web:557535b7bbe626efb28735',
    messagingSenderId: '1057753587696',
    projectId: 'iot2-affcc',
    authDomain: 'iot2-affcc.firebaseapp.com',
    databaseURL: 'https://iot2-affcc-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-affcc.firebasestorage.app',
    measurementId: 'G-3HM11MZ8D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AZx-PTkraCU9Nl3nW4c5ZHl_GfZrymU',
    appId: '1:1057753587696:android:cf4ac6a89bdb8992b28735',
    messagingSenderId: '1057753587696',
    projectId: 'iot2-affcc',
    databaseURL: 'https://iot2-affcc-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-affcc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz7EAZbKYOCMELCun4rv9Oahvci0DRtos',
    appId: '1:1057753587696:web:d1278c13fa83c054b28735',
    messagingSenderId: '1057753587696',
    projectId: 'iot2-affcc',
    authDomain: 'iot2-affcc.firebaseapp.com',
    databaseURL: 'https://iot2-affcc-default-rtdb.firebaseio.com',
    storageBucket: 'iot2-affcc.firebasestorage.app',
    measurementId: 'G-JHRDFTX7XN',
  );
}
